name: Deploy Next.js (Yarn, static export)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      NODE_ENV: production

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'yarn'

      - name: Restore .env file from secrets
        run: |
          echo "${{ secrets.ENV_FILE }}" > .env
          echo "✅ Restored .env file:"
          cat .env

      - name: Install dependencies
        run: yarn install --frozen-lockfile --production=false

      - name: Build static export with .env
        run: |
          yarn build
          yarn export
          tar -czf out.tgz -C out .

      - name: Upload build artifact to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          source: "out.tgz"
          target: "/home/ubuntu/muldum-v2/tmp"

      - name: Deploy static site to EC2 (Nginx)
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script_stop: true
          script: |
            set -e
            APP_DIR="/home/ubuntu/muldum-v2"
            TMP="$APP_DIR/tmp"
            WWW="/var/www/muldum-v2"

            echo "📦 Extracting static files to $WWW"
            sudo mkdir -p "$WWW"
            sudo tar -xzf "$TMP/out.tgz" -C "$WWW"
            sudo rm -f "$TMP/out.tgz"

            echo "✅ Deployed static site to Nginx root: $WWW"
            echo "🔁 Reloading Nginx..."
            sudo systemctl reload nginx
