name: Deploy via SSH

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ 저장소 Checkout
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ SSH로 원격 배포 실행
      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script_stop: true
          script: |
            set -e
            echo "🚀 Deploying to EC2..."

            cd /home/ubuntu/muldum-v2

            if [ -f ./deploy.sh ]; then
              echo "🔧 Running deploy.sh..."
              bash ./deploy.sh
            else
              echo "❌ deploy.sh not found!"
              exit 1
            fi

            echo "✅ Deployment completed successfully!"
